[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "setup"
version = "0.1"
dependencies = [
    "python-dotenv",
    "pyyaml",
    "requests",
    "nbformat",
    "beautifulsoup4"
]

[project.scripts]
backup = "utils.backup_tools:main"
set-dataset = "utils.set_dataset:main"
update-dependencies = "utils.get_dependencies:main"
install-dependencies = "utils.install_dependencies:main"
deic-storage-download = "utils.deic_storage_download:main"
update-readme = "utils.readme_templates:main"
reset-templates = "utils.code_templates:main"
code-examples = "utils.example_templates:main"
git-config = "utils.repo_tools:main"
ci-control = "utils.ci_tools:ci_control"
dcas-migration = "utils.dcas_migration:main"

[tool.setuptools.packages.find]
where = ["."]