[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "setup"
version = "0.1"
dependencies = [
    "python-dotenv",
    "pyyaml",
    "requests",
    "nbformat",
    "beautifulsoup4"
]

[project.scripts]
backup = "utils.ops.backup_tools:main"
set-dataset = "utils.rdm.dataset:main"
update-dependencies = "utils.ops.deps:main"
install-dependencies = "utils.install_dependencies:main"
update-readme = "utils.readme.template:main"
reset-templates = "utils.templates.code:main"
code-examples = "utils.templates.example:main"
git-config = "utils.ops.git_remote:main"
ci-control = "utils.ops.ci:ci_control"
dcas-migration = "utils.rdm.dcas:main"
dmp-update = "utils.rdm.dmp:main"
dmp-editor = "utils.rdm.editor:cli"

[tool.setuptools.packages.find]
where = ["."]